user_pref("accessibility.typeaheadfind", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.compactmode.show", true);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.download.always_ask_before_handling_new_types", true);
user_pref("browser.download.autohideButton", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.rows", 4);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 4);
user_pref("browser.search.suggest.enabled.private", true);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.startup.page", 3);
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.firstRunURL", "");
user_pref("devtools.command-button-measure.enabled", true);
user_pref("devtools.command-button-rulers.enabled", true);
user_pref("devtools.command-button-screenshot.enabled", true);
user_pref("devtools.dom.enabled", true);
user_pref("devtools.screenshot.audio.enabled", false);
user_pref("devtools.toolbox.host", "right");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.pocket.enabled", false);
user_pref("findbar.highlightAll", true);
user_pref("font.default.x-unicode", "sans-serif");
user_pref("font.default.x-western", "sans-serif");
user_pref("font.language.group", "zh-TW");
user_pref("font.name.monospace.ja", "Fira Code");
user_pref("font.name.monospace.ko", "Fira Code");
user_pref("font.name.monospace.x-unicode", "Fira Code");
user_pref("font.name.monospace.x-western", "Fira Code");
user_pref("font.name.monospace.zh-CN", "Fira Code");
user_pref("font.name.monospace.zh-HK", "Fira Code");
user_pref("font.name.monospace.zh-TW", "Fira Code");
user_pref("font.name.sans-serif.ja", "Noto Sans CJK JP");
user_pref("font.name.sans-serif.ko", "Noto Sans CJK KR");
user_pref("font.name.sans-serif.x-unicode", "Noto Sans");
user_pref("font.name.sans-serif.x-western", "Noto Sans");
user_pref("font.name.sans-serif.zh-CN", "Noto Sans CJK SC");
user_pref("font.name.sans-serif.zh-HK", "Noto Sans CJK HK");
user_pref("font.name.sans-serif.zh-TW", "Noto Sans CJK TC");
user_pref("font.name.serif.ja", "Noto Serif CJK JP");
user_pref("font.name.serif.ko", "Noto Serif CJK KR");
user_pref("font.name.serif.x-unicode", "Noto Serif");
user_pref("font.name.serif.x-western", "Noto Serif");
user_pref("font.name.serif.zh-CN", "Noto Serif CJK SC");
user_pref("font.name.serif.zh-HK", "Noto Serif CJK HK");
user_pref("font.name.serif.zh-TW", "Noto Serif CJK TC");
user_pref("font.size.monospace.x-unicode", 16);
user_pref("font.size.monospace.x-western", 16);
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("intl.accept_languages", "zh-tw,zh,en-us,en,ja");
user_pref("layout.css.color-mix.enabled", true);
user_pref("layout.css.has-selector.enabled", true);
user_pref("network.http.windows-sso.enabled", true);
user_pref("permissions.default.camera", 2);
user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.microphone", 2);
user_pref("permissions.default.xr", 2);
user_pref("places.history.expiration.max_pages", 2147483647);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("userChrome.DragSpace.Left.Disabled", true);
user_pref("userChrome.DragSpace.Right.Disabled", true);
user_pref("userChrome.DragSpace.Top.Windowed.Enabled", true);
user_pref("userChrome.EdgeTabs-Enabled", true);
user_pref("userChrome.NormalContextMenu-Enabled", true);
user_pref("userChrome.RegularMenuIcons-Enabled", true);
user_pref("userChrome.Toolbar.Transparency.Low.Enabled", true);
user_pref("userChrome.Windows.SystemEffects.Enabled", true);
