printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
rangeStart: 0
rangeEnd: .inf
requirePragma: false
insertPragma: false
proseWrap: always
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
